Add GitHub Actions workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,11 +52,21 @@ jobs:
     - name: Run Tempest script
       run: |
         cd epg-grabber
+        ls -la  # List files in the current directory to ensure correct location
         php tempest.php --epg config=tempest.config.xml invgz
-        rm -f tempest_config/epg/tempest_with_details.xml
-        rm -f tempest_config/epg/tempest.xml
+        ls -la tempest_config/epg  # List files before removal
 
-    # Step 8: Commit updated epg.xml
+# Step 8: Commit updated epg.xml
+    - name: Check files before running commit action
+      run: |
+        ls -la epg-grabber/tempest_config/epg
+        cat epg-grabber/tempest_config/epg/guide.xml || echo "File not found"
+
+    - name: Stage modified files
+      run: |
+        git add tempest_config/epg/*.xml
+        git status
+
     - name: Commit and push updated epg.xml
       uses: stefanzweifel/git-auto-commit-action@v4
       with:
